<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121102105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Ingredient table';
    }

    public function up(Schema $schema): void
    {
        // On crée UNIQUEMENT la table ingredient
        $this->addSql('CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BAF7870989D9B62 ON ingredient (slug)');
    }

    public function down(Schema $schema): void
    {
        // En cas de retour en arrière, on supprime ingredient
        $this->addSql('DROP TABLE ingredient');
    }
}