<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122095259 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE frigo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_frigo_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1D16CE116705DEF ON frigo (user_frigo_id)');
        $this->addSql('CREATE TABLE frigo_ingredient (frigo_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (frigo_id, ingredient_id))');
        $this->addSql('CREATE INDEX IDX_401FA2F9F6FDB9EF ON frigo_ingredient (frigo_id)');
        $this->addSql('CREATE INDEX IDX_401FA2F9933FE08C ON frigo_ingredient (ingredient_id)');
        $this->addSql('CREATE TABLE user_ingredient (user_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (user_id, ingredient_id))');
        $this->addSql('CREATE INDEX IDX_CCC8BE9CA76ED395 ON user_ingredient (user_id)');
        $this->addSql('CREATE INDEX IDX_CCC8BE9C933FE08C ON user_ingredient (ingredient_id)');
        $this->addSql('ALTER TABLE frigo ADD CONSTRAINT FK_A1D16CE116705DEF FOREIGN KEY (user_frigo_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE frigo_ingredient ADD CONSTRAINT FK_401FA2F9F6FDB9EF FOREIGN KEY (frigo_id) REFERENCES frigo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE frigo_ingredient ADD CONSTRAINT FK_401FA2F9933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_ingredient ADD CONSTRAINT FK_CCC8BE9CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_ingredient ADD CONSTRAINT FK_CCC8BE9C933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE frigo DROP CONSTRAINT FK_A1D16CE116705DEF');
        $this->addSql('ALTER TABLE frigo_ingredient DROP CONSTRAINT FK_401FA2F9F6FDB9EF');
        $this->addSql('ALTER TABLE frigo_ingredient DROP CONSTRAINT FK_401FA2F9933FE08C');
        $this->addSql('ALTER TABLE user_ingredient DROP CONSTRAINT FK_CCC8BE9CA76ED395');
        $this->addSql('ALTER TABLE user_ingredient DROP CONSTRAINT FK_CCC8BE9C933FE08C');
        $this->addSql('DROP TABLE frigo');
        $this->addSql('DROP TABLE frigo_ingredient');
        $this->addSql('DROP TABLE user_ingredient');
    }
}
