<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216095223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
       
        $this->addSql('CREATE TABLE user_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_active BOOLEAN DEFAULT NULL, user_id_id INT DEFAULT NULL, subscription_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_230A18D19D86650F ON user_subscription (user_id_id)');
        $this->addSql('CREATE INDEX IDX_230A18D1857C9F24 ON user_subscription (subscription_id_id)');
        $this->addSql('ALTER TABLE user_subscription ADD CONSTRAINT FK_230A18D19D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE user_subscription ADD CONSTRAINT FK_230A18D1857C9F24 FOREIGN KEY (subscription_id_id) REFERENCES subscription (id)');
  
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
      $this->addSql('ALTER TABLE user_subscriptions ADD CONSTRAINT fk_eaf92751857c9f24 FOREIGN KEY (subscription_id_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_subscriptions ADD CONSTRAINT fk_eaf927519d86650f FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    $this->addSql('ALTER TABLE user_subscription DROP CONSTRAINT FK_230A18D19D86650F');
        $this->addSql('ALTER TABLE user_subscription DROP CONSTRAINT FK_230A18D1857C9F24');
        $this->addSql('DROP TABLE user_subscription');
    }
}
