<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251217125551 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE diet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(45) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE diet_user (diet_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (diet_id, user_id))');
        $this->addSql('CREATE INDEX IDX_778B024CE1E13ACE ON diet_user (diet_id)');
        $this->addSql('CREATE INDEX IDX_778B024CA76ED395 ON diet_user (user_id)');
        $this->addSql('ALTER TABLE diet_user ADD CONSTRAINT FK_778B024CE1E13ACE FOREIGN KEY (diet_id) REFERENCES diet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE diet_user ADD CONSTRAINT FK_778B024CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE diet_user DROP CONSTRAINT FK_778B024CE1E13ACE');
        $this->addSql('ALTER TABLE diet_user DROP CONSTRAINT FK_778B024CA76ED395');
        $this->addSql('DROP TABLE diet');
        $this->addSql('DROP TABLE diet_user');
    }
}
