<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216080710 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price INT DEFAULT NULL, duration_months INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_active BOOLEAN DEFAULT NULL, user_id_id INT DEFAULT NULL, subscription_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAF927519D86650F ON user_subscriptions (user_id_id)');
        $this->addSql('CREATE INDEX IDX_EAF92751857C9F24 ON user_subscriptions (subscription_id_id)');
        $this->addSql('ALTER TABLE user_subscriptions ADD CONSTRAINT FK_EAF927519D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE user_subscriptions ADD CONSTRAINT FK_EAF92751857C9F24 FOREIGN KEY (subscription_id_id) REFERENCES subscription (id)');
      
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_subscriptions DROP CONSTRAINT FK_EAF927519D86650F');
        $this->addSql('ALTER TABLE user_subscriptions DROP CONSTRAINT FK_EAF92751857C9F24');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE user_subscriptions');
    }
}
